"use client";

import "./globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans"
});

// export const metadata = {
//     title: "Create T3 App",
//     description: "Generated by create-t3-app",
//     icons: [{ rel: "icon", url: "/favicon.ico" }]
// };

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    console.log(
        `${typeof window === "undefined" ? "SERVER" : "CLIENT"}: layout.tsx at: ${new Date().getTime()}`
    );
    return (
        <html lang="en">
            <body className={`font-sans ${inter.variable}`}>
                <nav>
                    <Link href="/">Home</Link>
                    <Link href="/client">Client</Link>
                    <Link href="/server">Server</Link>
                    <Link href="/composition">Composition</Link>
                </nav>
                {children}
            </body>
        </html>
    );
}
