import { NumberProvider } from "./context";
import { NumberProvider2 } from "./context2";

export const metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <NumberProvider>
            <NumberProvider2>{children}</NumberProvider2>
        </NumberProvider>
    );
}
